[package]
name = "cardstock-registry"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.70"
humantime-serde = "1.1.1"
log = "0.4.17"
serde = { version = "1.0.160", features = ["derive", "rc"] }
simplelog = "0.12.1"
toml = "0.7.3"
